model_args:
  pretrained_model_name_or_path: "/work/models/models/Qwen/Qwen2.5-7B-Instruct"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "/work/models/models/Qwen/Qwen2.5-7B-Instruct"
template_args:
  apply_chat_template: True
  system_prompt: You are a helpful assistant.
  user_start_tag: "<|im_start|>user\n"
  user_end_tag: "<|im_end|>"
  asst_start_tag: "<|im_start|>assistant\n"
  asst_end_tag: "<|im_end|>"
